modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "davebuildingmod"
version = "${version}"
displayName = "Dave's Building Extended"
authors = "SpaceDave, Rabbitminers"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.davebuildingmod]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.davebuildingmod]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.davebuildingmod]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"